import { SiReact, SiPreact, SiSvelte, SiNextdotjs, SiAngular, SiVuedotjs, SiShadcnui, SiFramer, SiNodedotjs, SiPython, SiRust, SiPhp, SiGit, SiFirebase, SiMojangstudios, SiCounterstrike, SiRoblox, SiAnycubic, SiFigma, SiAdobephotoshop, SiAdobeillustrator, SiSketch, SiOracle, SiTypescript, SiJavascript, SiLua, SiRuby, SiDocker, SiTerraform, SiAmazonwebservices, SiPostgresql, SiMysql, SiRedis, SiMongodb, SiRockstargames, SiValve, SiCanva, SiAffinitydesigner, SiInvision, SiCoreldraw,} from "react-icons/si";

export const technicalSkills = {
  frontend: [
    { name: 'React', icon: SiReact, url: 'https://react.dev/' },
    { name: 'Preact', icon: SiPreact, url: 'https://preactjs.com/' },
    { name: 'Svelte', icon: SiSvelte, url: 'https://svelte.dev/' },
    { name: 'Next.js', icon: SiNextdotjs, url: 'https://nextjs.org/' },
    { name: 'Angular', icon: SiAngular, url: 'https://angular.io/' },
    { name: 'Vue.js', icon: SiVuedotjs, url: 'https://vuejs.org/' },
    { name: 'Shadcn/ui', icon: SiShadcnui, url: 'https://ui.shadcn.com/' },
    { name: 'Framer Motion', icon: SiFramer, url: 'https://www.framer.com/motion/' },
  ],
  backend: [
    { name: 'Node.js', icon: SiNodedotjs, url: 'https://nodejs.org/' },
    { name: 'Express.js', icon: SiNodedotjs, url: 'https://expressjs.com/' },
    { name: 'Rocket.rs', icon: SiRust, url: 'https://rocket.rs/' },
    { name: 'PHP', icon: SiPhp, url: 'https://www.php.net/' },
    { name: 'Django', icon: SiPython, url: 'https://www.djangoproject.com/' },
    { name: 'Flask', icon: SiPython, url: 'https://flask.palletsprojects.com/' },
    { name: 'Ruby on Rails', icon: SiRuby, url: 'https://rubyonrails.org/' },
    { name: 'Docker', icon: SiDocker, url: 'https://www.docker.com/' },
  ],
  tools: [
    { name: 'Git', icon: SiGit, url: 'https://git-scm.com/' },
    { name: 'Firebase', icon: SiFirebase, url: 'https://firebase.google.com/' },
    { name: 'AWS', icon: SiAmazonwebservices, url: 'https://aws.amazon.com/' },
    { name: 'Terraform', icon: SiTerraform, url: 'https://www.terraform.io/' },
    { name: 'PostgreSQL', icon: SiPostgresql, url: 'https://www.postgresql.org/' },
    { name: 'MySQL', icon: SiMysql, url: 'https://www.mysql.com/' },
    { name: 'Redis', icon: SiRedis, url: 'https://redis.io/' },
    { name: 'MongoDB', icon: SiMongodb, url: 'https://www.mongodb.com/' },
  ],
  gamemanipulation: [
    { name: 'Minecraft', icon: SiMojangstudios, url: 'https://www.minecraft.net/' },
    { name: 'Counter-Strike', icon: SiCounterstrike, url: 'https://www.counter-strike.net/' },
    { name: 'Roblox', icon: SiRoblox, url: 'https://www.roblox.com/' },
    { name: 'Geometry Dash', icon: SiAnycubic, url: 'https://www.robtopgames.com/' },
    { name: 'Grand Theft Auto', icon: SiRockstargames, url: 'https://www.rockstargames.com/' },
    { name: 'Team Fortress 2', icon: SiValve, url: 'https://www.teamfortress.com/' },
    { name: 'Half-Life', icon: SiValve, url: 'https://www.half-life.com/' },
  ],
  design: [
    { name: 'Figma', icon: SiFigma, url: 'https://www.figma.com/' },
    { name: 'Adobe Photoshop', icon: SiAdobephotoshop, url: 'https://www.adobe.com/products/photoshop.html' },
    { name: 'Adobe Illustrator', icon: SiAdobeillustrator, url: 'https://www.adobe.com/products/illustrator.html' },
    { name: 'Sketch', icon: SiSketch, url: 'https://www.sketch.com/' },
    { name: 'InVision', icon: SiInvision, url: 'https://www.invisionapp.com/' },
    { name: 'Affinity Designer', icon: SiAffinitydesigner, url: 'https://affinity.serif.com/en-us/designer/' },
    { name: 'CorelDRAW', icon: SiCoreldraw, url: 'https://www.coreldraw.com/' },
    { name: 'Canva', icon: SiCanva, url: 'https://www.canva.com/' },
  ],
  language: [
    { name: 'Python', icon: SiPython, url: 'https://www.python.org/' },
    { name: 'JavaScript', icon: SiJavascript, url: 'https://www.javascript.com/' },
    { name: 'TypeScript', icon: SiTypescript, url: 'https://www.typescriptlang.org/' },
    { name: 'Rust', icon: SiRust, url: 'https://www.rust-lang.org/' },
    { name: 'Ruby', icon: SiRuby, url: 'https://www.ruby-lang.org/' },
    { name: 'Lua', icon: SiLua, url: 'https://www.lua.org/' },
    { name: 'Java', icon: SiOracle, url: 'https://www.java.com/' },
  ],
};
